### ISSUE TITLE
Accounts.get_token returns hashed token instead of raw token

### ISSUE THREAD

**Issue by alaister** [infinitered/authority_ecto#33]
Hi,
I'm not sure if this is an issue with Authority Ecto or the default Mithril code, but when I call `Accounts.get_token` it returns the hashed token from the database in the token struct instead of the raw token like when I call `Accounts.tokenize`. For example:
```
%MyApp.Accounts.Token{
   __meta__: #Ecto.Schema.Metadata<:loaded, "user_tokens">,
   expires_at: #DateTime<2018-06-17 10:31:32.000000Z>,
   id: "8daf165d-d9a2-4f4c-9416-0a97abefd7b4",
   inserted_at: #DateTime<2018-06-03 10:31:32.702569Z>,
   last_used_at: #DateTime<2018-06-03 10:31:32.702166Z>,
   purpose: :any,
   token: "49EE84AAFDC66FB2CD97088BE955A83DF710C8AE32C3A5A3BCEC3E047C66A908",
   updated_at: #DateTime<2018-06-03 10:31:32.702575Z>,
   user: #Ecto.Association.NotLoaded<association :user is not loaded>,
   user_id: "f63a2455-bd08-478c-8dae-0d429f68f319"
}
```
Instead of
```
%MyApp.Accounts.Token{
   __meta__: #Ecto.Schema.Metadata<:loaded, "user_tokens">,
   expires_at: #DateTime<2018-06-17 10:31:32Z>,
   id: "8daf165d-d9a2-4f4c-9416-0a97abefd7b4",
   inserted_at: #DateTime<2018-06-03 10:31:32.702569Z>,
   last_used_at: #DateTime<2018-06-03 10:31:32.702166Z>,
   purpose: :any,
   token: "2a559250-e30c-4c00-9cf1-0c9447958f0e",
   updated_at: #DateTime<2018-06-03 10:31:32.702575Z>,
   user: #Ecto.Association.NotLoaded<association :user is not loaded>,
   user_id: "f63a2455-bd08-478c-8dae-0d429f68f319"
 }
```
The result of this is that when I call `Accounts.authenticate` with the token struct from `Accounts.get_token` I get `{:error, :invalid_token}`.

My work around for the current Mithril codebase is to construct my own token struct in the same way the graphql layer does:
```
%Accounts.Token{token: token}
```

**Comment by danielberkompas** [comment]
This is intentional. If you look in the `Token` schema, you will see that the `:token` field type is a hashed field, using HMAC. This secures the token from leaking, even if the database table is read by a malicious actor.

The intent is that you hand the raw token to the client right after `tokenize`, and only use the token given back to you by the client. You do this through constructing a `Token` struct the way you said, `%Token{token: token_received_from_client}`.

If you want to store raw tokens in the database, simply change your `:token` field type to `:string` instead of `HMAC`.
